name: Build Wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release --out dist --no-sdist
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish-pypi:
    name: Publish wheels to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish wheels to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
